// packages/core/src/lib/components/slider/slider.svelte
<script lang="ts">
	import { Slider as ArkSlider } from "@ark-ui/svelte/slider";
	import { cn } from "$lib/utils.js";
	import type { ComponentProps } from "svelte";

	let {
		ref = $bindable(null),
		value = $bindable([0]),
		min = 0,
		max = 100,
		step = 1,
		disabled = false,
		orientation = "horizontal",
		class: className,
		...restProps
	}: ComponentProps<typeof ArkSlider.Root> = $props();
</script>

<ArkSlider.Root
	bind:ref
	bind:value
	{min}
	{max}
	{step}
	{disabled}
	{orientation}
	data-slot="slider"
	class={cn(
		"relative flex w-full touch-none items-center select-none data-disabled:opacity-50",
		orientation === "vertical" && "min-h-40 h-full w-auto flex-col",
		className
	)}
	{...restProps}
>
	<ArkSlider.Control class="relative flex w-full items-center">
		<ArkSlider.Track class="relative h-2 w-full grow overflow-hidden rounded-full bg-[var(--ui-muted)]">
			<ArkSlider.Range class="absolute h-full bg-[var(--ui-primary)]" />
		</ArkSlider.Track>
		<ArkSlider.Thumb index={0} class="block size-5 rounded-full border-2 border-[var(--ui-primary)] bg-[var(--ui-background)] shadow transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ui-ring)] focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50" />
	</ArkSlider.Control>
	<ArkSlider.HiddenInput />
</ArkSlider.Root>

// packages/react/src/components/Slider.tsx
import * as React from 'react';
import { Slider as ArkSlider } from '@ark-ui/react/slider';
import { cn } from '../utils.js';

export const SliderRoot = React.forwardRef<HTMLDivElement, React.ComponentPropsWithoutRef<typeof ArkSlider.Root>>(
  ({ className, ...props }, ref) => (
    <ArkSlider.Root
      ref={ref}
      className={cn('relative flex w-full touch-none select-none items-center', className)}
      {...props}
    />
  )
);
SliderRoot.displayName = 'SliderRoot';

export const SliderControl = React.forwardRef<HTMLDivElement, React.ComponentPropsWithoutRef<typeof ArkSlider.Control>>(
  ({ className, ...props }, ref) => (
    <ArkSlider.Control
      ref={ref}
      className={cn('relative flex w-full items-center', className)}
      {...props}
    />
  )
);
SliderControl.displayName = 'SliderControl';

export const SliderTrack = React.forwardRef<HTMLDivElement, React.ComponentPropsWithoutRef<typeof ArkSlider.Track>>(
  ({ className, ...props }, ref) => (
    <ArkSlider.Track
      ref={ref}
      className={cn('relative h-1.5 w-full grow overflow-hidden rounded-full bg-[var(--ui-muted)]', className)}
      {...props}
    />
  )
);
SliderTrack.displayName = 'SliderTrack';

export const SliderRange = React.forwardRef<HTMLDivElement, React.ComponentPropsWithoutRef<typeof ArkSlider.Range>>(
  ({ className, ...props }, ref) => (
    <ArkSlider.Range
      ref={ref}
      className={cn('absolute h-full bg-[var(--ui-primary)]', className)}
      {...props}
    />
  )
);
SliderRange.displayName = 'SliderRange';

export const SliderThumb = React.forwardRef<HTMLDivElement, React.ComponentPropsWithoutRef<typeof ArkSlider.Thumb>>(
  ({ className, ...props }, ref) => (
    <ArkSlider.Thumb
      ref={ref}
      className={cn(
        'block size-4 rounded-full border border-[var(--ui-primary)]/50 bg-[var(--ui-background)] shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--ui-ring)] disabled:pointer-events-none disabled:opacity-50',
        className
      )}
      {...props}
    />
  )
);
SliderThumb.displayName = 'SliderThumb';

export const SliderLabel = ArkSlider.Label;
export const SliderValueText = ArkSlider.ValueText;
export const SliderHiddenInput = ArkSlider.HiddenInput;

export const Slider = {
  Root: SliderRoot,
  Control: SliderControl,
  Track: SliderTrack,
  Range: SliderRange,
  Thumb: SliderThumb,
  Label: SliderLabel,
  ValueText: SliderValueText,
  HiddenInput: SliderHiddenInput
};
