// packages/react/src/components/Separator.tsx
import * as React from 'react';
import { cn } from '../utils.js';

export interface SeparatorProps extends React.HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical';
  decorative?: boolean;
}

export const Separator = React.forwardRef<HTMLDivElement, SeparatorProps>(
  (
    {
      className,
      orientation = 'horizontal',
      decorative = true,
      role = decorative ? 'none' : 'separator',
      ...props
    },
    ref
  ) => (
    <div
      ref={ref}
      role={role}
      aria-orientation={role === 'separator' ? orientation : undefined}
      className={cn(
        'shrink-0 bg-[var(--ui-border)]',
        orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
        className
      )}
      {...props}
    />
  )
);
Separator.displayName = 'Separator';

// packages/core/src/lib/components/separator/separator.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		orientation = "horizontal",
		"data-slot": dataSlot = "separator",
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		ref?: HTMLDivElement | null;
		orientation?: "horizontal" | "vertical";
	} = $props();
</script>

<div
	bind:this={ref}
	role="separator"
	data-slot={dataSlot}
	data-orientation={orientation}
	aria-orientation={orientation}
	class={cn(
		"shrink-0 bg-[var(--ui-border)]",
		orientation === "horizontal" ? "h-px w-full" : "w-px h-full",
		className
	)}
	{...restProps}
/>
